version: "3"

services:
  django-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: django
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=poke
      - DB_USER=postgres
      - DB_PASS=Empresarial

  db:
    image: postgres:10-alpine
    container_name: poke-db
    environment:
      - POSTGRES_DB=poke
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Empresarial
